### ISSUE TITLE
SSL/TLS

### ISSUE THREAD

**Issue by capoia** [setten-io/adonis-bull-queue#11]
is possible to conect to a redis server over ssl/tls? i have a digital ocean DB and i only works with ssl.

**Comment by miinion** [comment]
yes, 

in your config/queue.ts
make it like this

`
connection: {
    host: Env.get('QUEUE_REDIS_HOST'),
    port: Env.get('QUEUE_REDIS_PORT', 25061),
    password: Env.get('QUEUE_REDIS_PASSWORD'),
    username: 'default',
    tls: {}
  },
 `

**Comment by RomainLanz** [comment]
Have you been able to make it work @capoia?

**Comment by capoia** [comment]
> Have you been able to make it work @capoia?

yes! thank you.

**Comment by RomainLanz** [comment]
Great!
