### ISSUE TITLE
How to deploy in production without impacting performance ?

### ISSUE THREAD

**Issue by Glenn-o** [setten-io/adonis-bull-queue#5]
Hello, 

I would like to add the package in production on Heroku, and I'm afraid that it will impact the performance of the application, what is the best way to run it in production without impacting the performance?

Thanks

**Comment by brkn** [comment]
It shouldn't necessarily impact the performance of your application. As long as you have enough memory in your dyno, your application performance should stay same.

Just add another line in your procfile like this

```diff
release: node build/ace migration:run --force
web: node build/server.js
+ worker: node build/ace queue:listen
```

**Comment by RomainLanz** [comment]
Hey @Glenn-o! 👋🏻 

As @brkn said, there is nothing specific that should impact performance.

Did you have any issues?
